version: '3.8'
volumes:
  seq-data:
services:
  api:
    build : .
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB : cleanmediator
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA : Y
      SEQ_FIRSTRUN_ADMINPASSWORD: Admin123!
    ports:
      - "8081:80"
    volumes:
      - seq-data:/data
